[tool.poetry]
name = "aniverse"
version = "0.1.0"
description = ""
authors = ["thudoan1706"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
spacy = "^3.7.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
